version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./results:/app/results
    environment:
      - DATABASE_URL=sqlite:////app/resume_analyzer.db